#![feature(test)]

extern crate test;

use bio::alignment::sparse::*;
use test::Bencher;

static K_FACTOR: usize = 50;
static MATCH_SCORE: u32 = 1;
static GAP_OPEN: i32 = -1;
static GAP_EXTEND: i32 = -1;
static ALLOWED_MISMATCHES: usize = 3;
static MATCHES: &'static [(u32, u32)] = &[( 0, 50 ), ( 50, 100 ), ( 100, 150 ),
					  ( 150, 200 ), ( 200, 250 ), ( 250, 300 ), ( 300, 350 ), ( 350, 400 ),
					  ( 400, 450 ), ( 450, 500 ), ( 500, 550 ), ( 550, 600 ), ( 600, 650 ),
					  ( 650, 700 ), ( 700, 750 ), ( 750, 800 ), ( 800, 850 ), ( 850, 900 ),
					  ( 900, 950 ), ( 950, 1000 ), ( 1000, 1050 ), ( 1050, 1100 ), ( 1100, 1150 ),
					  ( 1150, 1200 ), ( 1200, 1250 ), ( 1250, 1300 ), ( 1300, 1350 ), ( 1350, 1400 ),
					  ( 1400, 1450 ), ( 1450, 1500 ), ( 1500, 1550 ), ( 1550, 1600 ), ( 1600, 1650 ),
					  ( 1650, 1700 ), ( 1700, 1750 ), ( 1750, 1800 ), ( 1800, 1850 ), ( 1850, 1900 ),
					  ( 1900, 1950 ), ( 1950, 2000 ), ( 2000, 2050 ), ( 2050, 2100 ), ( 2100, 2150 ),
					  ( 2150, 2200 ), ( 2200, 2250 ), ( 2250, 2300 ), ( 2300, 2350 ), ( 2350, 2400 ),
					  ( 2400, 2450 ), ( 2450, 2500 ), ( 2500, 2550 ), ( 2550, 2600 ), ( 2600, 2650 ),
					  ( 2650, 2700 ), ( 2700, 2750 ), ( 2750, 2800 ), ( 2800, 2850 ), ( 2850, 2900 ),
					  ( 2900, 2950 ), ( 2950, 3000 ), ( 3000, 3050 ), ( 3050, 3100 ), ( 3100, 3150 ),
					  ( 3150, 3200 ), ( 3200, 3250 ), ( 3250, 3300 ), ( 3300, 3350 ), ( 3350, 3400 ),
					  ( 3400, 3450 ), ( 3450, 3500 ), ( 3500, 3550 ), ( 3550, 3600 ), ( 3600, 3650 ),
					  ( 3650, 3700 ), ( 3700, 3750 ), ( 3750, 3800 ), ( 3800, 3850 ), ( 3850, 3900 ),
					  ( 3900, 3950 ), ( 3950, 4000 ), ( 4000, 4050 ), ( 4050, 4100 ), ( 4100, 4150 ),
					  ( 4150, 4200 ), ( 4200, 4250 ), ( 4250, 4300 ), ( 4300, 4350 ), ( 4350, 4400 ),
					  ( 4400, 4450 ), ( 4450, 4500 ), ( 4500, 4550 ), ( 4550, 4600 ), ( 4600, 4650 ),
					  ( 4650, 4700 ), ( 4700, 4750 ), ( 4750, 4800 ), ( 4800, 4850 ), ( 4850, 4900 ),
					  ( 4900, 4950 ), ( 4950, 5000 ), ( 5000, 5050 ), ( 5050, 5100 ), ( 5100, 5150 ),
					  ( 5150, 5200 ), ( 5200, 5250 ), ( 5250, 5300 ), ( 5300, 5350 ), ( 5350, 5400 ),
					  ( 5400, 5450 ), ( 5450, 5500 ), ( 5500, 5550 ), ( 5550, 5600 ), ( 5600, 5650 ),
					  ( 5650, 5700 ), ( 5700, 5750 ), ( 5750, 5800 ), ( 5800, 5850 ), ( 5850, 5900 ),
					  ( 5900, 5950 ), ( 5950, 5999 )];

static STR_1: &'static [u8] = b"TATGCACCAGAGTATGGAAGCATAAGCTCTGCATGCAAAGGTACATC\
TATGCACCAGAGTATGGAAGCATAAGCTCTGCATGCAAAGGTACATCAGATCCTGCGGTTGGGTGCCAACCCAAGTGTG\
TTCACGGGCGCTTGACAGACATCGGAGGATGGTGCACACTCACTCGACCAGCGCAAAGCACAGGATCTCACGGGCGGAC\
ATCTCTTAGGTCAGTCATCGTGGAGGAATGCTTGTACGTTCTTTTGGCTTCCCCTAACACGGCGGGCGTCTCCGGTACG\
TATCCTGTCGGTACACCCCTTAAGCCCCTAGGCCCGAAGAACATAGCGCATTTCACGCTCTCTACGAATGACCGCAACG\
ATCAAATGGGCGAGAACAACTAATTCCGATTCATGGGGTTTGTGGATTGTGACACAGCGCGCCCGCTACTGCGGGACGT\
GAGGACGCCCAATTCTGCCAAGGATTATTTAGGGTGTTTCACTAGAGTTATGCGCCGACCCCGGTTGGACCAGCTTGCA\
TTCGAAACTGCGTTACACAGCACCCCACCGCAATCGTATGACTCTCGCTGAAAAAGGGTGGTCAACCATTACACCTCTT\
ATGCCTGTTGTGGGAGGCTCGGTCTTAAGCAGCGCGCGAGCTGTGATCCAGGCTACCACGGACATAGTGTATGGAAAGT\
GATCCAGAGTAGACCCGCGGGGGCCTGACCTAACCTATATAAGTTGTATCGTGGCTATGAGGGTAGTCGCCGGAGAAAA\
CGTATGCTTACTGATTTTTAAGTCGGCGTGGCGCCGAAGCCGGATCGGTTGTAAGCTAGCCGGGCCTAGGGGTTCACCG\
TAACGGATTAGTCAAATTAAAATCCAGCGATGACTTCCTGATAGAACTCAAGTCGTGACCCCTCCGCTGCGGGCCTACA\
TCTGTTTTCGCAGGCGTGGTTGTTTACCAGGTATGGTGCTCATCTCTATTAGTCACGGGCAGCATGGTGTCACCGAACC\
GCGCGTCTCCTAATATCTGGTCTACCGATTTAGCCCCGGCAAATAACTTTGGATTGTGGTTGGAGAGTGCCAGAACTGA\
CGGGCGCTGCCGTGGGGCTCCTAACTAAAAACGCCACGGACCTGGCTAACATTCGTTGTTGACTATAACATTTGAGGGC\
GCTTCGGATTCCCCATACTGCCAGAGTATTATGTGGGTGGTAAACATAGATTCTATATAGTCAACGACATACACTCATT\
ATTATGCAATTGCGGCATCTCAACTATGTCTTAATTAGTTTTCCCGGATGGCGAAAACGATCTTACAGGAGAAGCGCTA\
CGCTGGTTTGGAAGACACTTAGTATCCTAGTAGTATGGGCTTGTGCGGGTCAACGGGCGCCGTCAAAGCGCACACATAT\
CTGGTGGGGACGGTGTCCCCTATCGGCGCACACGGGAGCCTAGGCAATCCCGACGTCCCGCGTGCTGGATAAAGAAAAG\
GCCGACTGCGCGAAATGAAGAATCGTCAATTTATTGTTGGCAGCTTTACAGTTCTTCTCCGCGGGCGGGCAGAGTGGTT\
TTAAGACCGGGGTCTATGCACAAGGGTGGAGCTTGATTACTATCATCGAAGGGTGACTTGCCGTGTTACAATCGACAAG\
CGAACGGCCGACTGCTTCGGCCCGCTGAGCGGACAACCTCCGATGTACCTACTCCATAGTAGACTTGGAAAACCCAGTC\
TTATGGCGCGGGGGAATCAAATGTGCCGATTCTTGACGAATAGTTCTAAGCCGAACTGCCAATCAGGGAAAAGTGTCGC\
GCACTAACTGGAGCTGAAACCGCCAATAGTGTCTAAGTTACTCTTCCCATCTATCAAGGTAAGCCTTTTCCGTACAGTT\
ATGACCATCTCACACTGGAAAGACGCACTGCATGCTCGGATGGAACTCGGAGATCACCTGGAAAGTCAGTGTCATGCGT\
GGCGGTTTAGTGTTCGACGTAAGAAAAACCTGGAAGACGGACGAGGTATGCAGACATTGCAGCAGTGGTAGTAGGGGTT\
ATACCCCTGGATTTAAAACTCACAACCTTCCTCATAGGCCTAAGGATCTTGCTAGACCTTAAGCAGGTACGTGGATCAG\
AATCGCTACTTCCTGTTAAGACTGTGGACCCTCCCACAAACTCCGATGCGAGCTAGGACGTCTTTAGCTCAGCTTGAGA\
ATACTCCTATTTGCCTTGAAAGCTGAGCGGTTCAGACAGAGTAACTACATCTTATATGTAACCACACTCACATAGTTGT\
TGGGGGCAAACAGCTAAGGATTCCTGGTCCCTGGCACGGATATAGATCACAATCTGGAATTCCCTCCTAAGTACCCGCC\
CGGTATTCCCACACTCTGTGAGACTACGTGCGCGTGTAGTATCGTGAGGTCCGCGGTGGAAAAGGGTTTGGCACTTACT\
ACTCAGTGACCGTATACACGGAGATTCGCACTGATGTGGAATATGAAATCCCACATCCCCTGAGAATTTCGAATCTGAG\
GATGAGTATATGCCTCGATGTAGGCCAGGAGCATTGATCCCGGCGTCGTCCGGTCTAAGCACCATAGTTATGGGTCGGT\
TATAAACGAATTTTGACGCGACGGGGAATGATACAGGATCCACAGTGAAACTAGTCTGGGCACCGATGCATTGCCAATG\
GTGCCTATTAGTGTTCCTGAAGTTGACTACAGTCCGTACCTCAGTATAGCGCTGGTTACTAGTAGCGAAGTTGAGATTG\
TAGCTCGTACTCCAATGACCACCCGAGGGGGTGGTGCAATGTGCAGGTAGGGGTAGGTTCCTGTAGTTCGGAGGTCAAC\
CTCTTGTTGACGTCTGATGCGAGCCTGACTAAAATGCGCTTCTTCACTTTTGTTCGTATAGTCACTATATTCGCGAAAC\
CGTCGCTTTTATTATAGACGGCCTACTTCTTTGACCGAGCCTCATAGTCTGCACTCGGGACGAAACTAACGGCTGTTCC\
ACTCATGACCTACGCGCCTGAGTGATCAAATAATCAAAAGAATGCGCCGCTATATGTAGGGGGCCCATGTATTGGCTGA\
CTTTGAAAACACTCTGACACGAACTTGATTGTCTTACTAGTGAGAGAGGGGGGAGATACGCAGGGCGCGGGAAAACGAT\
ATGCAGCTGTAGGGAGCGCTATTTGCTAGGGAGTATACAATCCAGGCCTCCCTCGCTCTCATCTTTATCTGTCGATCGT\
GAGCCAACGACTAGTTGGTCTATCGCGATTATTGCCACTATCGTTCCCACCCGCCCGTGTCGCCGTAGGAACAACCGGT\
CTTGCTACGGATGCTCTGATGTTTGTGCTAGTGGTCTAACGGTCCACGACAACAGTGTCGTATACAGGGCCACTCTTCG\
AAAGCGGCGTAAGCGCCACGCTTGTCCGCGAGTTGGGGACCTCGGGGAGTCCGTATTCTTTGAACCCTTGTTCAGGCGA\
GTGTTTTTGACGCCTTTCAACAATGCAGATCCCAGGGAGGTCCGGCCCTCTGTTCTATGAGTAGGTCAAGCTAGAACCG\
TGTTGTGAGAGGAATGAGGGTGCTTAAAGGGTTACCCGTCGTCACATACGTAAAAAGAATCCCTATTATCATGGACTCC\
AATCTCGCCACGTGAAAGTTAGCGGGGATAGCGTTTGGGTCTTGCATATCCTGGGCTCTTCGGCTACGGGTGGACACGA\
CATTGTTGATGGTGGTCGCGTAGAGCTAGCTTTTTACCTTATGGAAGGAGTTTCCGCACCCCCAGGGACGGGCTCCGGC\
CTCACTATGTTCAAAGCCCTAAATGCACATTCTAGTCTCCACGTGTTACAGTAGGGCCAAAGATGGCGTACTAACAGAT\
TGGTATTGGACTATAAAAGATGAGTGATTAAGATCTGAAGTTCAAGACGTCAGGCTTAAGTAGGAGTACCTTCTGGCAC\
GATAAGGACTCCTACCCCACATCCTGATAATGCAGCTATGTGGCAATTCACGCTTACCCAATCCTTAGCTGGCTAACAA\
TTCCCCATACATGTTCAGCGAAGGTAGAACAACCAAAAGCCCGTTGCGGAACTGGCCAATGCTATCCCAAGTTAGAAGG\
AATACGAACTGGTTCCGGGGACCAAGGCCCAGTTGGACATAATTTAACAACTCGGCGAAGATAGCAAGTTCTGGCGTCT\
GAACGTATTATTGTTGCTGGCTATCACAGTTAATTCCCTGCCTACGAATTTTGTCGTACCAATTCAATCCCCCTGGCGG\
AGCTCTATGTCCTAAGGCCCTGTTCAACTGCCGGATGATATTGTCTGGTTTCTGTGCCGTCGCTCAAACAATTCTAGGC\
CCCGAAACGATCAGAGGAACAACCGGGAATGTCGGCCGACTTCCAGCTCCGTCCTATATGCTAAGCGAAAACTTTACAC\
GAATCCAATACACATTTCTGCGAAGAGCTTTCACAAGGTACATTTTGCCGCCTTTTGAAGGATACGAACTCGGATATGT\
ACAAGAGACTCGGTCGTGCGGGAATCGCGAATTGCGGGAGTTAGGCACCCGGGTCAGACAATCCAGCGCAGACCTAGAC\
CTAACAAGAAGCACGCCAGCGTGCCCAATCCGGATAGTGGACGCTCCCCGGGTTTAGAAGCAAATAACCTAGGTGTACC\
TAACAATCGGCAACGCAGTTTTCTAGGATTCTAGCGTTTCTATCAGAACAAACAGATTCTTTGAGGGCTTAAATGGCGC\
CTTTTCCGTACAGCCACTAGGTATGTTAACGAACAACACCCTGCCTTTGACATGGCTCACGCTAGGCTTGTGAGCAAGG\
AGTAATCGACGGTTTGAGATCGCTTCTCGTCTAATATTAGACAACCTTGGTCGTCGTTGCCATATAACGACCAATGATT\
GGTTTCGGACTGCGACTAATACTGGTAGGTGGCCTGGCGGTGTTGGTGTGGACTGGTGGTGACCCGCACAGTGCAAGAG\
ATCATCAGGGACCATGCGATAAGGGACCATACGCGTATGCCCGTTTTGCGAGCAACGCGCGAAGCACAGCGTCTGGGGG\
CAACCCAGTTCGTCCTGCAATGCAGGATACGCTGTAACGGTGTGCCGAAGTATTCAAGGTGAAGACCAACCAGTCTCGT\
GTAATCCGTTCTAAGACGCACCCTTCTACTCTCTCCCGGTCACGTCGCGTACTTGGCGTGCACAACAAGAACAGATTGG\
TGACTCAGTAGAGCCTCGCCGACAGTTCCCTATCTTTCACCAGCGGATACCTACGAGTTAACCAATTACCAGGTGGGCG\
CAACTACCGATTGGACTACGCTATGTCGTCCGGCTCCTGTTCAAGTAAATCCGTGGAGGTAAACTACCACCCGGATGTA\
AAACTCCGAGGTTCGTTCTATAGTCCCTTGGTCCGCAAATCGCCCTGTGGGTTAGGGATTATAAAATACACAGATTATA\
AACGTCGATAAAAGTAGGTACTGCACGGAGGGGTCTAACAAATAGATGATGTGGTCATCCACTCCGTCCTGAACACTAG\
CTGAGATTCCCGCCCAGAGAAGTTAATCATTTTTAAGGCCCGACGGAGGCACCTAGACGCCACGCTGCACTCTCTATCC\
CCTAAGCGGCTCAGGCGACTACTTCGGTTACCTGGTAACCAAGTGGCTTGAAAGTTCTTCCTCTTGTGGCACGAAAGTT\
CTGGGATCCGCCGAGGGGGGGTGTACTCAGAATGCTTCCTGGTGCGCTGAGCCGCTAGTGCTCACATATTAGACATTAA\
TCTGCTCTTAATTATCCTATAGAGGAGCATCGGGACCGTGAAAACAAAAAACGACCAACGAATCATTCCAAGACTTAGC\
TCAACCTGCCATTTTAAGTAATACGAATGTCAGGATACACCGGTAAAAGGTACCAGTCTGAGCAGTCCTTGATAGAGCC\
CAGTTAGGCAGTGCGATGATCTCACCAGGGAGAGATGGCACTTAGGGAACTCCTGTCATCACACTTTACATCGGCCTTC\
CTACAGACAGTTTGAATCAGCCTTCTGGAAGTGAATAGAAGGCATAGTATAGCTCCTGGCGAAGCTTGTGATACT";

static STR_2: &'static [u8] = b"GTAGAGTGCAAGTAGTGGTCCATTTACAAGTTGACCTTCCACCACTG\
GTAGAGTGCAAGTAGTGGTCCATTTACAAGTTGACCTTCCACCACTGAACCCGGTCTCAGGTGTTGGGTTATACAGTCA\
CGCCACCGAGACCGTTGCTGATCACCGAAAGGCAATCCAGGAACTTGGAGGATACGGGATGCTGATAACTAGAGGGAGT\
GCTAGTACAGGCCCCATATGCGGCACAACACAAATAGATATGATGCTTCCTGTGATACGGATCCTCAATACGCAGCTAC\
CCGAAGGCAAAAGTCCACATGTTCGACTATCTTGGCTTTGGTGTGACCAAGACGTGTGCGGCAGAGAGGACGTTCGCCA\
GCAGGCACCGCGTATCCCAACTTGAGGTTTCGCTAAATCCTTCATTGGCTGGATGAGGGGGTAAAGGTGGTCTCGGGAC\
GTCTCGTGTGGACCGAAAACTTGTCTACGAGCTCAGCCAGGCTTGGCGAATGCCGAAACGAGAGTGTTCGTCCTGACTG\
GTGGGGGCCTACCTACAGACCTCAGTGTTAGCGCCTATAATGGAGGGCTGTGGACTAACATTCAGGTGCGTGGAGTCCC\
CACGACTGGCGATAGCGGCAGTTACTGGTTGCCGCACAGGCCTATTCGTAGCCTTTAAGAGGGGCACGGTTTCACGCTG\
TTACGCCGAGGACCGATCACCCGGAAGGCTCTCATCTCGTATGGGTACTTAGGCCGATTCCCCGCGCCAAACTTCAACC\
CAAAAGACGTTGAGTAGTCAACAGGATCATTGTGTCGTGAGGATAATCAGGATGGGGCCGTAGTAACGACGGCCTTTGC\
CAAGCCTAAAGGCGTTTTGAAAGTGAGTGTTTTGAAGATCTCCTCCAGCGGGGGCTCGCTCCGGAGGTGCATTAAGCCA\
CCGCCCCACGAAAGTATATCGGCTTCAATGCGTGTTCCTCTAATGCTGGATTATTGGCCGTGGAACAGCTCGGAACTAG\
TTATACTGCCCGCTTTCGTTCAAGGTCACCAGGGCCCTATCTTCGATCCGTAGCCGCCTAGAAAGGAATATAGCTGCAG\
GAATCGCTTTATCGGATAGTTACTCCCCTCGCCACCGCCCATGAATATATTGACCCCAGGCATCTCACCTGCTCTTACC\
GGTGAAGATCCAGATCTGATACATTGGTATATGTGCGAGGTGACGACTGGCGCGATCCGGATCTTCTCATGCCCTACCC\
CAACTATTTTCACCGGTATCCCTCTTTATTAAAAGTCGTCTGGCGATCTCAGATTTAGGTACGACCTTGCCTTTTCTCC\
GAACCTAAAAAGCTTGAATGTTTTGCTGAGGTGCTTGCCGACGCCACTCAGTGACTAGCATGGAAGGAAATTTATAGTC\
CAAGGTGGAATAGAGGACGCAGATGAGGCCCCACCGGGTTGGCTACGAAGGGTAAGCGACGGGCCAACCGCGTCAAGCA\
GAGGGATGAACTTGTAATTCTTTTTATATCGCACTTCTTGATGTTTGCCCAGGTAGAAAGAGATTTTTTGACAGGTTCG\
TCTAGCTGAACTTCCGGTCGGTTTGCTCCCTACCAATTCTTCGTCATGAGGTGCGGAGTAGCCCCTCGATGGCCATCGG\
CGGGCCATGCTATTTTCAGCATCTTTTTTGCTTCAGATTAGAGCGCACAGAGTTTTAAGTTACATGACGTATGTTAAGA\
TGTCCGAGTCTACTTGTGCCTAGGGCCAGGGGATGACTTCGAAGGTCACAACCCGAAGAGACAAGTACGCTATCCTGGG\
GAGATTCCAATACTTGGGTGGAAGTTTGTTGCCTCTAGGGCTGCGCCCTGGCCTGTAATGACTCGCCTAGTACGCCCGG\
GAGTGGGTTACCCATAGGATTCCAGAGTATATAGCTGAGCGTCCAGCCACTCGTGCGTACACCGAGGCGCTCGTCAGCT\
TCCCCTTCACCTATGGCGGTCCGACTACCGAGAAGCTACACTTAGGAATTTTGCAAGTTTTTATGCTTAAGGTAACAAT\
CCACTGTCCCCTCGAGTGGTGCCGGCCTACATAGAGTCGCCTCGAACGCGAATTAGCTTTTCTGACTTAGTCCGCAGTG\
TCAGCTACCTAAATAAAGACCGGGTTCTGTCGCTAACAGACTCGAATTCTTTCAGGATACCGCTGTTGTACACTAGGGC\
TACGGCTCCAGGACTCAGATAGCTAGGCCGTAATATGGAAGTTAAATCAACTGACCAAGAACTGGGGATACTCTCTTTT\
TGCAGTGTTAACAGTTCACGCACCTAAACGGCGCGACTTGAATAAACACCTACGGCTATCATGAAAGAAAGTTATGTCC\
TAGTTTGAACGAAGTTTTGTGTTTCAAAAACGGAGGGTAACAGCCACGGAAAATAGTACTTCTTCTCGTTCAGGGTTCA\
CGGGCCCGACCGATGGGCCTTTGAAGCCTCCTTCTTCAAGCTTTTTCAGCCGTCTCGATAGACCCACGGAGAGCGCTCA\
CTGGTTGATAGGTGGTACGTAAAATGGGTACCACCAATATATTTTCCCAATGGTGGTACTTTCTAACCCCACTGACGGC\
GTACCGAACTGGTATGCTTTATTCAATGCCCGCTGTCACCATCAACTCCGCAACAATATTGCAGGGATACCACTTTCGA\
CACCCGTCTTGGATGTGTTCCCCATGTTGTGTCCCGGCCTGCGTTCACCTCTCTATTTAAGAAAGGAACGACTTTTCGC\
GCGGATACACATCCCGTGGTTGAGGGTGTAACTTGGGTTGGAGCATGTCCCACCACAGAGTCTGGATTCACGCGATCAG\
AACGTTCAGGCACTCTCACCAAAACTGGCCAGCATCCAGTCAGAGGAAGCATCCAGCTGACCGTGAGATGCCTTCCGAA\
AAGTGAGCATCTCGACATTTGTACGGGAATGATTATTTTGCAACCACATCGGATGCACACGTGAACAATATATGGATTG\
GGAGTCACGAAATAGCTTACTCATTGCCATTTAGACTAGGTTTGACGGGCCAGGGCCTTCGCGTGGCGGGGATTCGAAC\
GTGGCAATTCGTATGGCGTAGATGTCAACAGAGCGGGTACCCGCGCTTCATTCCTGCGTTGGATCTCTCGAGTGGATGG\
TGCGGTTACAAGTACTTGTGAAACTTCCCGTAAGGCGGCCCTTTGGGTAGGGCGTCTCTGGAAGCGATTAGTGCGACAG\
ATCACCGCACCATGGGGTAAAAAGCTACTTCGTCATGAGCTATGCAGTCAGTAGGCCATGGCCTCGGCCAATAATAGCA\
CATGAACACGTCGTATTCTCCTCCATTGTCAGTAATTGCTTGTTTTGGCGTTCGCGGAGAATCCAATCTCCCGGTGCTT\
CAGCTCATTATCCTGACGAGGCGTCCCGTCCCGATCGGGAGAAGGAATTAGCGTATCGGTAAATGGATTGCAGGAGCTG\
AGCATACAACAGAGAACTGTATAAGCTATGGACTCGTCGGAACCGATAGGAATTCCCAGTCTAGCCCCGGCTCGAACGG\
CACGGAATAAACGGCGATGGAACGATTGTAAAGATACTAAGCACCTTCCCTACGTAAAAGGGAAACTAACCCTAGCCTA\
GCGTTTGAGGACTCCTAAGCGACATCCAACAGCTGCAGGATAAATGTACCTAAATCCCTTGCATCCCTCGTCATTTGCT\
CTTGTTAGAGACTTCGGTCGTCTTTCCTCGAACGCGGGGCCAGGCCGATATCCCACAGCTATGACAAGGTGTTTCAAGC\
ACAGAGTAGTCACGGACCTCTCGGGCTCCGTGCGGTTGCTGTAAAGTAGGGCTATCCTCAGGGCACATACAAGGAAATG\
ACGTTCAATTCCCCCGACGAACTTAGCGGTCTTTGCCAAGGTAATCATTCTGTTAGAATGGTTTCCACCGGTGGCACTA\
GGACCCTGGTGTAGCCAGAATTGTTGATGCCCTCTTGGCAATCACTCTCGAGGAGGGTCGTTTCTGATGAATAACATCG\
TGCTCCGTTTTTTACGGACCGTTTTCCCGAGGCTGACGCAGTCTTAGCCGGATTTCTCATGGCAGCGCTGGTGAAGCGA\
CGTGTTACTTGTACGCACAGTTGCGACATTGGAGGCATGTTTAACAGGGCTACGTCAGAAGCCCTTCCCCGGCCACCGG\
GCGCAGCGGTTATGGATATAGCAACACGTGACCTTCATTTTCACCCGCCCACTTCGAGCCTCAACCTGGCCCCGCTCAA\
ACAAGGACGTGAGGATCTGGGCGTGTTTGGAGCCATTGCGGCCCGGCTACCACCGCGGATATTCTTTGATAACCGGTAT\
TACTGTGCAGAGTGTCGGTGATGAGTGCTTGACGTCCAGAAAGCCTACTCGATCTCCTTATCGCGCCAATTTCCGTCTT\
TAACGACTCCGGTAGGATCCCCCTATGAAGGAATATGCCATACGACTCTTCCCGCTGCGCTGAATGTACAGCAGGCCGA\
CCGTCCTTGTGGCCATTGCACCGTAAGCTCCCAGACCAAGGTAAACGTGACTCCTGGCCAGATTGAATGGCGGCGTAAG\
ATGTGACTAGTCCGTATGTAATTCGTAGTCCTCATGTTAACCGGCACGCAGACGAGCAATGTGGCCCCCAACCGTCACT\
AGCACATCGGGCACAGAGATCCTCTACGTCTGTCATTCAAGACCGACGGCCGTGTGTACCCGCGCCTCCCTCGAGCGTG\
GGGCGCACCCGAAGCGGTGACATACATCTAAATTAAGAAAACACTCGAGCGATACTGCTCATCTAGGTGAGATTCTACC\
GATAGATAGCGCGCTACCAATTGCCGATATCTATCGTACCCCCCGGATTGCCGGAGCAGGCGTGGAACGTCCCCTGAGG\
GACATGGCAATAATGTAGCTACTGGAAGGTGCTACCATGGCCAGCTAAGTCGTTGGATCTACGCAGTGAGCAGTCGCCA\
TTGGTCCAGTAACTCCGGAAGCTGACCATTACACGCTAGTCAACTTTTCTTCCGAATTACTGCGTTCATAGACCATATT\
CGCTGCCGTAGCTAGAGTTTGTGTGGAGATGTAATCCTGATATAGAGATCAGCAACAACGGATTCATCCCTATGGTAGC\
CCCACCGAGAACAGCTTCTAGGAAACGCCCTATGGGCAGTGAATAACTCCGATGCTTCATCTTATCGATGGTGCTGTTC\
CCGCTAAAAGAAATTAGCAGATATAGTACCGAAGCGACGGCCCACAGGCCAGTGGTCAGAGGTCGGTTTACCATTAACT\
CAACTCCACGCCTAGCCGTGACCGGAGGCGACTCCGTTGATGCTCATGCCGACGTGTTGATCAATAAGTGAAGAGATCA\
TCCTCCCAAGGCCTTCTGCAATGGAGTTAGAGGATATCGTCGCAGGTTGGTCACTGGATCGAATTCACAATTAGCAAGA\
CACATGTCCCAGCCGCTCGCTCGAGCCTTCTATGCTTCTATGAGGGCCTCCGAGGGCCCTATGTCCTAACTGGGCTCTC\
CGCGCACGAGCCCTGCGTCTATGACTTGACCAGTGAGTGGTTACTCACGTCGTCATCGGATCCACTTTCGGTGCCCGTA\
AATCACGGGCCAACCGAATGGTCTGACCCCCAAAACGATTGGCATATGCCGACGGACTGGTCCTTCAGCTACAGTGTAA\
TTTTCATCCGCTATGGCCCCGCAAGATGTTATGTTACGGCCCGTTCAACTCGTTAACGTAATGTCCAAGCATAGCTATA\
CGACTTAAAATGCTGGCCGACAAGGCCGAGTATTAATATGCACCGTTCTTTCTGCTAATATGACTGTTCATGATTGCGG\
TTGTTAATAAACACTGGAGGGACTGGGCTAGTTCCGTGGAGGTCTCGTACTGACGTATAAATATCTTGTGTCAGCCGCG\
ATTTCGTTTCGTCGTGCGTGTGGGCCCAAATCAAGACATTTCGGCCATACCGTGGGACTTGAACTGTGAAAGAGGCAAG\
CCTGGGTGCCTGGTTCACTCAACAAGAATTCAGCAAAGTTGCGCAGTCTCCAGTGAAGCCTGCAAGTGCATTGAG";

#[bench]
fn bench_lcskpp(b: &mut Bencher) {
    b.iter( || lcskpp(MATCHES, K_FACTOR) );
}

#[bench]
fn bench_sdpkpp(b: &mut Bencher) {
    b.iter( || sdpkpp(MATCHES, K_FACTOR, MATCH_SCORE, GAP_OPEN, GAP_EXTEND) );
}

#[bench]
fn bench_sdpkpp_union_lcskpp_path(b: &mut Bencher) {
    b.iter( || sdpkpp_union_lcskpp_path( MATCHES, K_FACTOR, MATCH_SCORE, GAP_OPEN, GAP_EXTEND) );
}

#[bench]
fn bench_find_kmer_matches(b: &mut Bencher) {
    b.iter( || find_kmer_matches(STR_1, STR_2, K_FACTOR) );
}

#[bench]
fn bench_hash_kmers(b: &mut Bencher) {
    b.iter( || hash_kmers(STR_1, K_FACTOR) );
}

#[bench]
fn bench_find_kmer_matches_seq1_hashed(b: &mut Bencher) {
    b.iter( || find_kmer_matches_seq1_hashed(&hash_kmers(STR_1, K_FACTOR ),
					    STR_2, K_FACTOR) );
}

#[bench]
fn bench_find_kmer_matches_seq2_hashed(b: &mut Bencher) {
    b.iter( || find_kmer_matches_seq2_hashed(STR_1, &hash_kmers(STR_2, K_FACTOR), K_FACTOR) );
}
    
#[bench]
fn bench_expand_kmer_matches(b: &mut Bencher) {
    b.iter( || expand_kmer_matches(STR_1, STR_2, K_FACTOR, MATCHES, ALLOWED_MISMATCHES) );
}
